### ISSUE TITLE
.srt files from ccsubs.com all get times of -1

### ISSUE THREAD

**Issue by Lone-Coder** [AlexPoint/SubtitlesParser#5]
Download a .srt file from http://ccsubs.com/ and all the times that are parsed are set to -1.

I expect it is because all of the caption items are rounded to the nearest second so they fail to parse correctly.

**Comment by AlexPoint** [comment]
Indeed, the srt file format must specify the number of milliseconds in the timecodes (see http://forum.doom9.org/showthread.php?p=470941#post470941)
I checked a few of their subtitles and indeed, their timecodes look strange (you have overlaps, no ms specified...)
Anyway, I loosened the condition on the srt parser so that even timecodes without ms are parsed correctly: https://github.com/AlexPoint/SubtitlesParser/commit/1495e69bbcfb1791c01ec636f90597e8f84c0023
A new nuget package (1.4.7 has been released with those changes)
